language: c
sudo: required
dist: trusty

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f6341f97901850a796ee
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

compiler:
 - gcc
 - clang

env:
 - RUN_TEST=1 BUILD_CONFIG=""
 - RUN_TEST=1 BUILD_CONFIG="-DOpenVML_ARCH=generic -DOpenVML_CPU_CORENAME=generic -DAUTO_DETECT_CPU=OFF"
 - RUN_TEST=0 BUILD_CONFIG="-DOpenVML_ARCH=x86_64 -DOpenVML_CPU_CORENAME=sandybridge -DAUTO_DETECT_CPU=OFF"
 - RUN_TEST=0 BUILD_CONFIG="-DOpenVML_ARCH=x86_64 -DOpenVML_CPU_CORENAME=haswell -DAUTO_DETECT_CPU=OFF"


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y cmake

install:
- if [ "$CC" = "gcc" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

script:
 - mkdir ./build_test
 - cd ./build_test
 - cmake --version
 - cmake $BUILD_CONFIG ..
 - make
 - cd ./test/
 - if [ $RUN_TEST -eq 1 ]; then ./run_vml_test; fi
 - if [ $RUN_TEST -eq 1 ]; then ./misc_test; fi
