language: c
sudo: false
compiler:
 - gcc
 - clang

env:
 - RUN_TEST=1 BUILD_CONFIG=""
 - RUN_TEST=1 BUILD_CONFIG="-DOpenVML_ARCH=generic -DOpenVML_CPU_CORENAME=generic -DAUTO_DETECT_CPU=OFF"
 - RUN_TEST=0 BUILD_CONFIG="-DOpenVML_ARCH=x86_64 -DOpenVML_CPU_CORENAME=sandybridge -DAUTO_DETECT_CPU=OFF"
 - RUN_TEST=0 BUILD_CONFIG="-DOpenVML_ARCH=x86_64 -DOpenVML_CPU_CORENAME=haswell -DAUTO_DETECT_CPU=OFF"


before_install:
 # Install cmake 2.8.12
 - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz
 - tar xf cmake-2.8.12.tar.gz
 - cd cmake-2.8.12
 - ./bootstrap --system-curl --prefix=$HOME/usr
 - make
 - make install
 - cd ..
 # End install cmake


install:
- if [ "$CC" = "gcc" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

script:
 - mkdir ./build_test
 - cd ./build_test
 - $HOME/usr/bin/cmake --version
 - $HOME/usr/bin/cmake $BUILD_CONFIG ..
 - make
 - cd ./test/
 - if [ $RUN_TEST -eq 1 ]; then ./run_vml_test; fi
 - if [ $RUN_TEST -eq 1 ]; then ./misc_test; fi
