language: c
compiler:
 - gcc
 - clang

before_install:
 - sudo add-apt-repository --yes ppa:sschuberth/cmake-here
 - sudo apt-get update -qq
 - sudo apt-get install cmake

script:
 - mkdir ./build_test
 - cd ./build_test
 - cmake --version
 - cmake ..
 - make
 - cd ./test/
 - ./run_vml_test
 - ./misc_test
