language: c
sudo: false
compiler:
 - gcc
 - clang

before_install:
 # Install cmake 2.8.12
 - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz
 - tar xf cmake-2.8.12.tar.gz
 - cd cmake-2.8.12
 - ./bootstrap --system-curl --prefix=$HOME/usr
 - make
 - make install
 - cd ..
 # End install cmake

script:
 - mkdir ./build_test
 - cd ./build_test
 - $HOME/usr/bin/cmake --version
 - $HOME/usr/bin/cmake ..
 - make
 - cd ./test/
 - ./run_vml_test
 - ./misc_test
