language: c
compiler:
 - gcc
 - clang

before_install:
 - sudo apt-get remove cmake cmake-data
 - sudo apt-get update -qq
 # Install cmake 2.8.12
 - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.tar.gz
 - tar xf cmake-2.8.12.tar.gz
 - cd cmake-2.8.12
 - ./bootstrap --system-curl
 - make
 - sudo make install
 - cd ..
 # End install cmake

script:
 - mkdir ./build_test
 - cd ./build_test
 - cmake --version
 - cmake ..
 - make
 - cd ./test/
 - ./run_vml_test
 - ./misc_test
